// Generated by CoffeeScript 2.7.0
(function() {
  var all, popular, unwanted;

  popular = ['pepperoni', 'sausage', 'cheese'];

  unwanted = ['anchovies', 'olives'];

  all = [...popular, ...unwanted, 'mushrooms'];

  console.log(all);

}).call(this);
