// Generated by CoffeeScript 2.7.0
(function() {
  var data, mood;

  if (singing) {
    mood = greatlyImproved;
  }

  if (happy && knowsIt) {
    clapsHands();
    chaChaCha();
  } else {
    showIt();
  }

  data = friday ? sue : jill;

}).call(this);
