// Generated by CoffeeScript 2.7.0
(function() {
  var filename, i, len;

  for (i = 0, len = list.length; i < len; i++) {
    filename = list[i];
    (function(filename) {
      if (filename !== '.DS_Store' && filename !== 'Thumbs.db' && filename !== 'ehthumbs.db') {
        return fs.readFile(filename, function(err, contents) {
          return compile(filename, contents.toString());
        });
      }
    })(filename);
  }

}).call(this);
