// Generated by CoffeeScript 2.7.0
(function() {
  var awardMedals, contenders, gold, rest, sliver;

  gold = sliver = rest = 'unknown';

  awardMedals = function(first, second, ...others) {
    gold = first;
    sliver = second;
    return rest = others;
  };

  contenders = ["Michael Phelps", "Liu Xiang", "Yao Ming", "Allyson Felix", "Shawn Johnson", "Roman Sebrle", "Guo Jingjing", "Tyson Gay", "Asafa Powell", "Usain Bolt"];

  awardMedals(contenders);

  console.log(`Gold: ${gold}
Sliver: ${sliver}
The Field: ${rest.join(', ')}`);

}).call(this);
