// Generated by CoffeeScript 2.7.0
(function() {
  var currentUser, user;

  user = {
    name: 'Werner Heisenberg',
    occupation: 'theoretical physicist'
  };

  currentUser = {
    ...user,
    status: 'Uncertain'
  };

}).call(this);
