// Generated by CoffeeScript 2.7.0
(function() {
  var changeNumber, inner, outer;

  outer = 1;

  changeNumber = function() {
    var inner;
    inner = -1;
    return outer = 10;
  };

  inner = changeNumber();

}).call(this);
